spring:
    config:
      activate:
        on-profile: local
    h2:
        console:
            enabled: true

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password:

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true

springdoc:
    packages-to-scan: com.wearedaezzok.daezzokserver
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /api-docs/json
        groups:
            enabled: true
